"""Core utilities module."""
from app.core.exceptions import (
    BadRequestError,
    ConflictError,
    ExternalServiceError,
    ForbiddenError,
    NotFoundError,
    RateLimitError,
    SabiTaxException,
    UnauthorizedError,
    ValidationError,
)
from app.core.security import (
    create_access_token,
    create_password_reset_token,
    create_refresh_token,
    decode_token,
    get_token_subject,
    hash_password,
    verify_password,
    verify_password_reset_token,
)
from app.core.utils import (
    calculate_compliance_score,
    calculate_monthly_paye,
    calculate_nigerian_pit,
    calculate_vat,
    format_naira,
    generate_filing_reference,
    generate_referral_code,
    generate_tin_reference,
    get_next_tax_due_date,
    get_tax_year,
    mask_account_number,
    mask_tin,
)

__all__ = [
    # Exceptions
    "SabiTaxException",
    "NotFoundError",
    "UnauthorizedError",
    "ForbiddenError",
    "BadRequestError",
    "ConflictError",
    "ValidationError",
    "RateLimitError",
    "ExternalServiceError",
    # Security
    "verify_password",
    "hash_password",
    "create_access_token",
    "create_refresh_token",
    "decode_token",
    "get_token_subject",
    "create_password_reset_token",
    "verify_password_reset_token",
    # Utils
    "format_naira",
    "generate_referral_code",
    "generate_tin_reference",
    "generate_filing_reference",
    "mask_tin",
    "mask_account_number",
    "calculate_nigerian_pit",
    "calculate_monthly_paye",
    "calculate_vat",
    "get_next_tax_due_date",
    "get_tax_year",
    "calculate_compliance_score",
]
